"""Real Skandiamäklarna office performance data.

Source: Kontorslista_RGG_Jan-feb_2025-260316_vHK.xlsx (internal office-list
with revenue, sold objects, PROBLEM/UTMANINGAR/OK triage and priority 1-5)
supplied by the user 2026-07. Period 250101-250618 vs. same period prior year.

This module holds the INTERNAL PERFORMANCE LAYER only (revenue, category,
priority, comments) — not office identity data (address/phone/manager),
which should come from the live scraper (scraper.py) once available.
Coordinates are approximate (city-level), used for map placement.
"""
from __future__ import annotations

# 80 kontor med tilldelad prioritet (huvudlistan i underlaget)
REAL_OFFICES: list[dict] = [
    {
        "name": 'Skandiamäklarna Malmö',
        "city": 'Malmö',
        "region": 'Skåne',
        "lat": 55.605, "lng": 13.0038,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 12005678, "oms_fjol": 17190350,
        "sald": 225, "sald_fjol": 326,
        "yoy_pct": -30.2,
        "kommentar": 'Ledarskapet, utöka FT med nya',
        "recommended_action": 'Störst kontor i nätverket men -30% oms — akut. Boka ledarskapsgenomlysning med franchisetagaren inom 2 veckor. Utred om tappet är marknad eller internt (jämför med Skåne-snittet). Starta rekrytering av 2-3 erfarna mäklare parallellt, och utred behov av delägare/ny FT-partner för att avlasta ledningen.',
    },
    {
        "name": 'Skandiamäklarna Stockholm Vasastan',
        "city": 'Stockholm Vasastan',
        "region": 'Stockholm',
        "lat": 59.3428, "lng": 18.0447,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 9971912, "oms_fjol": 9680560,
        "sald": 124, "sald_fjol": 127,
        "yoy_pct": 3.0,
        "kommentar": 'Utöka FT',
        "recommended_action": 'Stabilt men platt (+3%) i ett av landets starkaste lägen — outnyttjad potential. Hjälp franchisetagaren identifiera och rekrytera 1-2 säljare för att utöka kapaciteten; inget akut ledarskapsproblem, snarare en tillväxtmöjlighet.',
    },
    {
        "name": 'Skandiamäklarna Enskede/Trångsund',
        "city": 'Enskede/Trångsund',
        "region": 'Stockholm',
        "lat": 59.278, "lng": 18.088,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 8087232, "oms_fjol": 6616278,
        "sald": 117, "sald_fjol": 116,
        "yoy_pct": 22.2,
        "kommentar": 'Nya FT alt utöka, Ingen X-faktor,',
        "recommended_action": "Växer (+22%) men saknar 'X-faktor' enligt kommentaren — bräcklig tillväxt utan stark profil. Följ upp med coachning kring säljkultur/varumärke och överväg en profilstark nyrekrytering för att befästa momentumet.",
    },
    {
        "name": 'Skandiamäklarna Tyresö/Älta',
        "city": 'Tyresö/Älta',
        "region": 'Stockholm',
        "lat": 59.243, "lng": 18.283,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 5846598, "oms_fjol": 6421593,
        "sald": 111, "sald_fjol": 129,
        "yoy_pct": -9.0,
        "kommentar": 'För bekväma, Utöka FT samt mäklare',
        "recommended_action": "-9% och teamet beskrivs som 'för bekväma'. Inför tydliga aktivitetsmål/KPI:er, se över incitamentsstruktur och rekrytera minst en driven mäklare för att bryta bekvämligheten.",
    },
    {
        "name": 'Skandiamäklarna Jönköping',
        "city": 'Jönköping',
        "region": 'Småland',
        "lat": 57.7826, "lng": 14.1618,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 5064024, "oms_fjol": 5245108,
        "sald": 98, "sald_fjol": 99,
        "yoy_pct": -3.5,
        "kommentar": 'Ledarskapet, attraktion, X-faktor',
        "recommended_action": '-3,5%, ledarskap och arbetsgivarattraktivitet pekas ut som grundproblem. Starta ett lokalt employer branding-initiativ och ge franchisetagaren ledarskapsstöd/coachning; svårt att rekrytera sig ur problemet utan det.',
    },
    {
        "name": 'Skandiamäklarna Örebro',
        "city": 'Örebro',
        "region": 'Örebro län',
        "lat": 59.2741, "lng": 15.2066,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 3729830, "oms_fjol": 4765044,
        "sald": 83, "sald_fjol": 114,
        "yoy_pct": -21.7,
        "kommentar": 'Petra behöver all hjälp som finns.',
        "recommended_action": "-22%, kommentaren är tydlig: 'Petra behöver all hjälp som finns'. Prioritera ett fysiskt platsbesök snarast och sätt ihop ett fullt stödpaket (rekrytering, marknadsföring, ops) — detta är ett av de mest akuta fallen.",
    },
    {
        "name": 'Skandiamäklarna Stockholm Kungsholmen',
        "city": 'Stockholm Kungsholmen',
        "region": 'Stockholm',
        "lat": 59.3325, "lng": 18.0304,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 2445510, "oms_fjol": 1547350,
        "sald": 41, "sald_fjol": 27,
        "yoy_pct": 58.0,
        "kommentar": 'Allt behövs',
        "recommended_action": "+58% — stark tillväxt, men taggad 'Allt behövs'. Bekräfta att tillväxten är uthållig (inte tillfällig) och säkerställ att franchisetagaren får det operativa stöd som efterfrågas innan kontoret skalar vidare.",
    },
    {
        "name": 'Skandiamäklarna Haninge',
        "city": 'Haninge',
        "region": 'Stockholm',
        "lat": 59.167, "lng": 18.1441,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 1995722, "oms_fjol": 2560213,
        "sald": 32, "sald_fjol": 57,
        "yoy_pct": -22.0,
        "kommentar": 'VÄSTERHANINGE!, Byte behövs!',
        "recommended_action": "-22%, 'Byte behövs!' med fokus på Västerhaninge. Inled en utvärdering av nuvarande franchisetagare med sikte på ett ägarbyte, och kartlägg Västerhaninge som eget fokusområde i övergången.",
    },
    {
        "name": 'Skandiamäklarna Stockholm Södermalm',
        "city": 'Stockholm Södermalm',
        "region": 'Stockholm',
        "lat": 59.3157, "lng": 18.071,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 1479528, "oms_fjol": 1387610,
        "sald": 23, "sald_fjol": 22,
        "yoy_pct": 6.6,
        "kommentar": 'Inga KPIER/fokusområden',
        "recommended_action": '+6,6% men helt utan KPI:er eller fokusområden. Enkel men viktig åtgärd: installera ett grundläggande uppföljningsramverk (mål, veckovisa KPI:er) — sannolikt en snabb vinst.',
    },
    {
        "name": 'Skandiamäklarna Sundbyberg',
        "city": 'Sundbyberg',
        "region": 'Stockholm',
        "lat": 59.3606, "lng": 17.9711,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 1406000, "oms_fjol": 1675624,
        "sald": 20, "sald_fjol": 31,
        "yoy_pct": -16.1,
        "kommentar": 'Uöka med flera FT och mäklare',
        "recommended_action": '-16%, behöver fler FT och mäklare. Rekrytera ytterligare en franchisetagarpartner samt 2-3 säljare; hantera i par med Solna (samma rotorsak enligt kommentaren).',
    },
    {
        "name": 'Skandiamäklarna Solna',
        "city": 'Solna',
        "region": 'Stockholm',
        "lat": 59.36, "lng": 18.0,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 1218698, "oms_fjol": 2636480,
        "sald": 22, "sald_fjol": 52,
        "yoy_pct": -53.8,
        "kommentar": 'Samma som Sundbyberg',
        "recommended_action": '-54% — största tappet i hela listan för ett aktivt kontor. Kommentaren pekar på samma orsak som Sundbyberg. Slå ihop åtgärdsplanen med Sundbyberg och prioritera högst inom hela Prio 1-gruppen givet omfattningen av tappet.',
    },
    {
        "name": 'Skandiamäklarna Danderyd',
        "city": 'Danderyd',
        "region": 'Stockholm',
        "lat": 59.402, "lng": 18.035,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 1213048, "oms_fjol": 1511380,
        "sald": 17, "sald_fjol": 12,
        "yoy_pct": -19.7,
        "kommentar": None,
        "recommended_action": '-20% utan dokumenterad orsak. Boka diagnossamtal med franchisetagaren för att kartlägga grundorsak innan åtgärd sätts — högvärdesområde där tappet är svårförklarat.',
    },
    {
        "name": 'Skandiamäklarna Österåker/Vaxholm',
        "city": 'Österåker/Vaxholm',
        "region": 'Stockholm',
        "lat": 59.4797, "lng": 18.2966,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 1161700, "oms_fjol": 845192,
        "sald": 19, "sald_fjol": 10,
        "yoy_pct": 37.4,
        "kommentar": 'Ny FT följt av rekrytering',
        "recommended_action": '+37% och redan en plan: ny FT på plats, rekrytering pågår. Följ upp och ge stöd i onboardingen av den nya franchisetagaren samt rekryteringsstöd.',
    },
    {
        "name": 'Skandiamäklarna Vällingby/Hässelby',
        "city": 'Vällingby/Hässelby',
        "region": 'Stockholm',
        "lat": 59.3654, "lng": 17.8734,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 1075640, "oms_fjol": 1962620,
        "sald": 34, "sald_fjol": 63,
        "yoy_pct": -45.2,
        "kommentar": 'Allt fel! Rambod är en varumärkesrisk',
        "recommended_action": "-45%, allvarligast i kvalitativ mening: 'Allt fel! Rambod är en varumärkesrisk'. Detta är sannolikt ett franchise-ärende snarare än ett rekryteringsärende — eskalera för juridisk/avtalsmässig genomgång av samarbetet.",
    },
    {
        "name": 'Skandiamäklarna Stockholm Östermalm',
        "city": 'Stockholm Östermalm',
        "region": 'Stockholm',
        "lat": 59.3358, "lng": 18.0889,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 869660, "oms_fjol": 453598,
        "sald": 14, "sald_fjol": 6,
        "yoy_pct": 91.7,
        "kommentar": None,
        "recommended_action": '+92% utan kommentar — starkast i gruppen. Förstå vad som driver framgången och använd kontoret som best practice-exempel för övriga Stockholmskontor.',
    },
    {
        "name": 'Skandiamäklarna Norrtälje',
        "city": 'Norrtälje',
        "region": 'Stockholm',
        "lat": 59.7581, "lng": 18.7042,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 440880, "oms_fjol": 388680,
        "sald": 8, "sald_fjol": 8,
        "yoy_pct": 13.4,
        "kommentar": 'Byte behövs',
        "recommended_action": "+13% men ändå 'Byte behövs'. Planera ett kontrollerat ägarbyte som inte stör den positiva utvecklingen — inte ett akut nödläge, men bör hanteras proaktivt.",
    },
    {
        "name": 'Skandiamäklarna Täby',
        "city": 'Täby',
        "region": 'Stockholm',
        "lat": 59.4439, "lng": 18.0687,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 376142, "oms_fjol": 946472,
        "sald": 6, "sald_fjol": 17,
        "yoy_pct": -60.3,
        "kommentar": None,
        "recommended_action": '-60% utan dokumenterad orsak — näst största tappet i listan. Prioritera platsbesök/diagnossamtal snarast; högt Stockholmsläge som inte bör tappa så kraftigt oförklarat.',
    },
    {
        "name": 'Skandiamäklarna Trångsund/Skogås/Sköndal',
        "city": 'Trångsund/Skogås/Sköndal',
        "region": 'Stockholm',
        "lat": 59.228, "lng": 18.087,
        "kategori": 'PROBLEM',
        "prio": '1', "prio_num": 1.0,
        "oms": 0, "oms_fjol": 0,
        "sald": 0, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": None,
        "recommended_action": '0 kr i omsättning — kontoret är i praktiken vilande. Ta ett aktivt beslut: nystart med ny franchisetagare, eller formell avveckling och omfördelning av området till grannkontor.',
    },
    {
        "name": 'Skandiamäklarna Västerås',
        "city": 'Västerås',
        "region": 'Mälardalen',
        "lat": 59.6099, "lng": 16.5448,
        "kategori": 'OK',
        "prio": '2', "prio_num": 2.0,
        "oms": 8189497, "oms_fjol": 7997966,
        "sald": 154, "sald_fjol": 164,
        "yoy_pct": 2.4,
        "kommentar": 'Rekrytera och ta in delägare',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Sollentuna',
        "city": 'Sollentuna',
        "region": 'Stockholm',
        "lat": 59.428, "lng": 17.951,
        "kategori": 'UTMANINGAR',
        "prio": '2', "prio_num": 2.0,
        "oms": 4845806, "oms_fjol": 3450740,
        "sald": 87, "sald_fjol": 60,
        "yoy_pct": 40.4,
        "kommentar": 'Ingen X-faktor',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Borås',
        "city": 'Borås',
        "region": 'Västra Götaland',
        "lat": 57.721, "lng": 12.9401,
        "kategori": 'PROBLEM',
        "prio": '2', "prio_num": 2.0,
        "oms": 3218060, "oms_fjol": 3288276,
        "sald": 66, "sald_fjol": 82,
        "yoy_pct": -2.1,
        "kommentar": 'Få mäklare, dålig energi, tillväxt behövs',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Lidingö',
        "city": 'Lidingö',
        "region": 'Stockholm',
        "lat": 59.3656, "lng": 18.1353,
        "kategori": 'PROBLEM',
        "prio": '2', "prio_num": 2.0,
        "oms": 2518078, "oms_fjol": 2548448,
        "sald": 38, "sald_fjol": 37,
        "yoy_pct": -1.2,
        "kommentar": 'Rekrytering påbörjad, utöka FT, Helena är igång',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Sundsvall',
        "city": 'Sundsvall',
        "region": 'Norrland',
        "lat": 62.3908, "lng": 17.3069,
        "kategori": 'PROBLEM',
        "prio": '2', "prio_num": 2.0,
        "oms": 1237867, "oms_fjol": 1170261,
        "sald": 33, "sald_fjol": 31,
        "yoy_pct": 5.8,
        "kommentar": 'Rekrytering och delägare',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Vemdalen/Funäsdalen',
        "city": 'Vemdalen/Funäsdalen',
        "region": 'Norrland',
        "lat": 62.4467, "lng": 13.9439,
        "kategori": 'UTMANINGAR',
        "prio": '2', "prio_num": 2.0,
        "oms": 1212360, "oms_fjol": 994520,
        "sald": 22, "sald_fjol": 20,
        "yoy_pct": 21.9,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Hisingen',
        "city": 'Hisingen',
        "region": 'Västra Götaland',
        "lat": 57.7208, "lng": 11.937,
        "kategori": 'PROBLEM',
        "prio": '2', "prio_num": 2.0,
        "oms": 883620, "oms_fjol": 675800,
        "sald": 19, "sald_fjol": 20,
        "yoy_pct": 30.8,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Nynäshamn',
        "city": 'Nynäshamn',
        "region": 'Stockholm',
        "lat": 58.9042, "lng": 17.9467,
        "kategori": 'PROBLEM',
        "prio": '2', "prio_num": 2.0,
        "oms": 77520, "oms_fjol": 267600,
        "sald": 1, "sald_fjol": 6,
        "yoy_pct": -71.0,
        "kommentar": 'Hitta ny FT',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Lund',
        "city": 'Lund',
        "region": 'Skåne',
        "lat": 55.7047, "lng": 13.191,
        "kategori": 'PROBLEM',
        "prio": '2', "prio_num": 2.0,
        "oms": 0, "oms_fjol": 0,
        "sald": 0, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": 'Behöver startas upp. Landgren har option',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Järfälla',
        "city": 'Järfälla',
        "region": 'Stockholm',
        "lat": 59.4222, "lng": 17.8353,
        "kategori": 'UTMANINGAR',
        "prio": '3', "prio_num": 3.0,
        "oms": 4590896, "oms_fjol": 4367720,
        "sald": 112, "sald_fjol": 102,
        "yoy_pct": 5.1,
        "kommentar": 'Rekrytering och ledarskap',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Älvsjö/Årsta',
        "city": 'Älvsjö/Årsta',
        "region": 'Stockholm',
        "lat": 59.2751, "lng": 18.0113,
        "kategori": 'UTMANINGAR',
        "prio": '3', "prio_num": 3.0,
        "oms": 4577850, "oms_fjol": 4222350,
        "sald": 89, "sald_fjol": 84,
        "yoy_pct": 8.4,
        "kommentar": 'Följa den fortsatta utvecklingen',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Hjo/Karlsborg/Skövde/Tibro/Tidaholm',
        "city": 'Hjo/Karlsborg/Skövde/Tibro/Tidaholm',
        "region": 'Västra Götaland',
        "lat": 58.3911, "lng": 13.8458,
        "kategori": 'OK',
        "prio": '3', "prio_num": 3.0,
        "oms": 4304150, "oms_fjol": 3686080,
        "sald": 77, "sald_fjol": 65,
        "yoy_pct": 16.8,
        "kommentar": 'Behöver gå upp i marknadsandel',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Eskilstuna',
        "city": 'Eskilstuna',
        "region": 'Mälardalen',
        "lat": 59.3706, "lng": 16.5077,
        "kategori": 'UTMANINGAR',
        "prio": '3', "prio_num": 3.0,
        "oms": 3905531, "oms_fjol": 5850585,
        "sald": 94, "sald_fjol": 123,
        "yoy_pct": -33.2,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Uppsala',
        "city": 'Uppsala',
        "region": 'Mälardalen',
        "lat": 59.8586, "lng": 17.6389,
        "kategori": 'UTMANINGAR',
        "prio": '3', "prio_num": 3.0,
        "oms": 3726780, "oms_fjol": 3997706,
        "sald": 93, "sald_fjol": 95,
        "yoy_pct": -6.8,
        "kommentar": 'Få mäklare, dålig tillväxt/au',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Upplands Väsby',
        "city": 'Upplands Väsby',
        "region": 'Stockholm',
        "lat": 59.5188, "lng": 17.9152,
        "kategori": 'UTMANINGAR',
        "prio": '3', "prio_num": 3.0,
        "oms": 1819410, "oms_fjol": 1481164,
        "sald": 41, "sald_fjol": 40,
        "yoy_pct": 22.8,
        "kommentar": 'Driv och säljengagemang behövs',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Örnsköldsvik',
        "city": 'Örnsköldsvik',
        "region": 'Norrland',
        "lat": 63.2909, "lng": 18.7153,
        "kategori": 'PROBLEM',
        "prio": '3', "prio_num": 3.0,
        "oms": 370820, "oms_fjol": 330780,
        "sald": 8, "sald_fjol": 9,
        "yoy_pct": 12.1,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Trollhättan',
        "city": 'Trollhättan',
        "region": 'Västra Götaland',
        "lat": 58.2837, "lng": 12.2886,
        "kategori": 'PROBLEM',
        "prio": '3', "prio_num": 3.0,
        "oms": 319200, "oms_fjol": 235040,
        "sald": 8, "sald_fjol": 6,
        "yoy_pct": 35.8,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Mölndal',
        "city": 'Mölndal',
        "region": 'Västra Götaland',
        "lat": 57.6554, "lng": 12.0134,
        "kategori": 'PROBLEM',
        "prio": '3', "prio_num": 3.0,
        "oms": 277944, "oms_fjol": 508392,
        "sald": 6, "sald_fjol": 11,
        "yoy_pct": -45.3,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Enköping/Sala',
        "city": 'Enköping/Sala',
        "region": 'Mälardalen',
        "lat": 59.6362, "lng": 17.0777,
        "kategori": 'PROBLEM',
        "prio": '3', "prio_num": 3.0,
        "oms": 0, "oms_fjol": 206956,
        "sald": 0, "sald_fjol": 4,
        "yoy_pct": -100.0,
        "kommentar": 'Västerås har haft option',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Märsta/Sigtuna',
        "city": 'Märsta/Sigtuna',
        "region": 'Stockholm',
        "lat": 59.6259, "lng": 17.8478,
        "kategori": 'PROBLEM',
        "prio": '3', "prio_num": 3.0,
        "oms": 0, "oms_fjol": 0,
        "sald": 0, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Göteborg Väster',
        "city": 'Göteborg Väster',
        "region": 'Västra Götaland',
        "lat": 57.696, "lng": 11.913,
        "kategori": 'OK',
        "prio": '4', "prio_num": 4.0,
        "oms": 5755756, "oms_fjol": 5255930,
        "sald": 117, "sald_fjol": 103,
        "yoy_pct": 9.5,
        "kommentar": 'Områdesrisk i Gbg, Bygga tillväxt i GbG',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Nacka',
        "city": 'Nacka',
        "region": 'Stockholm',
        "lat": 59.3106, "lng": 18.1636,
        "kategori": 'OK',
        "prio": '4', "prio_num": 4.0,
        "oms": 5236305, "oms_fjol": 4393996,
        "sald": 104, "sald_fjol": 87,
        "yoy_pct": 19.2,
        "kommentar": 'Ledarskap, låg rekrytering',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Gävle',
        "city": 'Gävle',
        "region": 'Gävleborg',
        "lat": 60.6749, "lng": 17.1413,
        "kategori": 'OK',
        "prio": '4', "prio_num": 4.0,
        "oms": 4687573, "oms_fjol": 3734986,
        "sald": 117, "sald_fjol": 101,
        "yoy_pct": 25.5,
        "kommentar": 'Oms/mäklare, X-faktor',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Botkyrka/Salem',
        "city": 'Botkyrka/Salem',
        "region": 'Stockholm',
        "lat": 59.2, "lng": 17.833,
        "kategori": 'UTMANINGAR',
        "prio": '4', "prio_num": 4.0,
        "oms": 4488905, "oms_fjol": 3693386,
        "sald": 77, "sald_fjol": 65,
        "yoy_pct": 21.5,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Hägersten',
        "city": 'Hägersten',
        "region": 'Stockholm',
        "lat": 59.3034, "lng": 17.9764,
        "kategori": 'UTMANINGAR',
        "prio": '4', "prio_num": 4.0,
        "oms": 4367896, "oms_fjol": 3317000,
        "sald": 81, "sald_fjol": 64,
        "yoy_pct": 31.7,
        "kommentar": 'Fortsatt rekryteringsbehov och expansion',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Värmdö',
        "city": 'Värmdö',
        "region": 'Stockholm',
        "lat": 59.3167, "lng": 18.4833,
        "kategori": 'OK',
        "prio": '4', "prio_num": 4.0,
        "oms": 3468000, "oms_fjol": 2591300,
        "sald": 43, "sald_fjol": 40,
        "yoy_pct": 33.8,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Falun',
        "city": 'Falun',
        "region": 'Dalarna',
        "lat": 60.6065, "lng": 15.6355,
        "kategori": 'UTMANINGAR',
        "prio": '4', "prio_num": 4.0,
        "oms": 1532840, "oms_fjol": 1649644,
        "sald": 34, "sald_fjol": 33,
        "yoy_pct": -7.1,
        "kommentar": 'Ledarskap',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Upplands Bro',
        "city": 'Upplands Bro',
        "region": 'Stockholm',
        "lat": 59.5, "lng": 17.75,
        "kategori": 'OK',
        "prio": '4', "prio_num": 4.0,
        "oms": 1102400, "oms_fjol": 1730090,
        "sald": 27, "sald_fjol": 39,
        "yoy_pct": -36.3,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Karlskrona',
        "city": 'Karlskrona',
        "region": 'Blekinge',
        "lat": 56.1612, "lng": 15.5869,
        "kategori": 'UTMANINGAR',
        "prio": '4', "prio_num": 4.0,
        "oms": 946248, "oms_fjol": 0,
        "sald": 13, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": 'Ledarskap och rekrytering',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Saltsjöbaden',
        "city": 'Saltsjöbaden',
        "region": 'Stockholm',
        "lat": 59.2833, "lng": 18.3,
        "kategori": 'OK',
        "prio": '4', "prio_num": 4.0,
        "oms": 717100, "oms_fjol": 513220,
        "sald": 10, "sald_fjol": 8,
        "yoy_pct": 39.7,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Hässleholm',
        "city": 'Hässleholm',
        "region": 'Skåne',
        "lat": 56.1589, "lng": 13.7668,
        "kategori": 'UTMANINGAR',
        "prio": '4', "prio_num": 4.0,
        "oms": 16000, "oms_fjol": 360000,
        "sald": 0, "sald_fjol": 8,
        "yoy_pct": -95.6,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Stockholms Skärgård',
        "city": 'Stockholms Skärgård',
        "region": 'Stockholm',
        "lat": 59.45, "lng": 18.7,
        "kategori": 'PROBLEM',
        "prio": '4', "prio_num": 4.0,
        "oms": 6000, "oms_fjol": 338800,
        "sald": 0, "sald_fjol": 2,
        "yoy_pct": -98.2,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Gnesta',
        "city": 'Gnesta',
        "region": 'Mälardalen',
        "lat": 59.05, "lng": 17.3,
        "kategori": 'PROBLEM',
        "prio": '4', "prio_num": 4.0,
        "oms": 0, "oms_fjol": 65360,
        "sald": 0, "sald_fjol": 1,
        "yoy_pct": -100.0,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Trelleborg',
        "city": 'Trelleborg',
        "region": 'Skåne',
        "lat": 55.3753, "lng": 13.1567,
        "kategori": 'PROBLEM',
        "prio": '4', "prio_num": 4.0,
        "oms": 0, "oms_fjol": 0,
        "sald": 0, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Linköping',
        "city": 'Linköping',
        "region": 'Östergötland',
        "lat": 58.4109, "lng": 15.6216,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 12157546, "oms_fjol": 12106808,
        "sald": 260, "sald_fjol": 256,
        "yoy_pct": 0.4,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Norrköping',
        "city": 'Norrköping',
        "region": 'Östergötland',
        "lat": 58.5877, "lng": 16.1924,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 11575763, "oms_fjol": 9213858,
        "sald": 269, "sald_fjol": 206,
        "yoy_pct": 25.6,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Karlstad',
        "city": 'Karlstad',
        "region": 'Värmland',
        "lat": 59.3793, "lng": 13.5036,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 10747926, "oms_fjol": 8059725,
        "sald": 215, "sald_fjol": 164,
        "yoy_pct": 33.4,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Helsingborg',
        "city": 'Helsingborg',
        "region": 'Skåne',
        "lat": 56.0465, "lng": 12.6945,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 9608615, "oms_fjol": 8161172,
        "sald": 173, "sald_fjol": 160,
        "yoy_pct": 17.7,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Kristianstad',
        "city": 'Kristianstad',
        "region": 'Skåne',
        "lat": 56.0294, "lng": 14.1567,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 8689820, "oms_fjol": 6260420,
        "sald": 143, "sald_fjol": 99,
        "yoy_pct": 38.8,
        "kommentar": 'Tappa mäklare?',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Nyköping/Oxelösund',
        "city": 'Nyköping/Oxelösund',
        "region": 'Mälardalen',
        "lat": 58.7527, "lng": 17.0083,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 8264252, "oms_fjol": 6341755,
        "sald": 157, "sald_fjol": 152,
        "yoy_pct": 30.3,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Huddinge',
        "city": 'Huddinge',
        "region": 'Stockholm',
        "lat": 59.2369, "lng": 17.9819,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 6457151, "oms_fjol": 5269536,
        "sald": 108, "sald_fjol": 96,
        "yoy_pct": 22.5,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Spånga',
        "city": 'Spånga',
        "region": 'Stockholm',
        "lat": 59.3833, "lng": 17.9,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 4401200, "oms_fjol": 3629303,
        "sald": 53, "sald_fjol": 44,
        "yoy_pct": 21.3,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Ystad',
        "city": 'Ystad',
        "region": 'Skåne',
        "lat": 55.4295, "lng": 13.8204,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 4296381, "oms_fjol": 4989814,
        "sald": 74, "sald_fjol": 91,
        "yoy_pct": -13.9,
        "kommentar": 'Rullar på',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Höör',
        "city": 'Höör',
        "region": 'Skåne',
        "lat": 55.9333, "lng": 13.5333,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 4281260, "oms_fjol": 2304704,
        "sald": 65, "sald_fjol": 34,
        "yoy_pct": 85.8,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Strängnäs',
        "city": 'Strängnäs',
        "region": 'Mälardalen',
        "lat": 59.3778, "lng": 17.0311,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 3836256, "oms_fjol": 3069564,
        "sald": 92, "sald_fjol": 74,
        "yoy_pct": 25.0,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Mjölby',
        "city": 'Mjölby',
        "region": 'Östergötland',
        "lat": 58.3236, "lng": 15.1284,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 3182425, "oms_fjol": 2693659,
        "sald": 66, "sald_fjol": 55,
        "yoy_pct": 18.1,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Bromma',
        "city": 'Bromma',
        "region": 'Stockholm',
        "lat": 59.34, "lng": 17.94,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 2773320, "oms_fjol": 0,
        "sald": 51, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Motala',
        "city": 'Motala',
        "region": 'Östergötland',
        "lat": 58.5372, "lng": 15.0367,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 2342420, "oms_fjol": 756720,
        "sald": 46, "sald_fjol": 18,
        "yoy_pct": 209.5,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Kävlinge',
        "city": 'Kävlinge',
        "region": 'Skåne',
        "lat": 55.7942, "lng": 13.1119,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 1930650, "oms_fjol": 1710236,
        "sald": 36, "sald_fjol": 35,
        "yoy_pct": 12.9,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Sandviken',
        "city": 'Sandviken',
        "region": 'Gävleborg',
        "lat": 60.6167, "lng": 16.7667,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 1733186, "oms_fjol": 925100,
        "sald": 47, "sald_fjol": 26,
        "yoy_pct": 87.4,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Trosa',
        "city": 'Trosa',
        "region": 'Mälardalen',
        "lat": 58.9042, "lng": 17.5528,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 1586124, "oms_fjol": 1268340,
        "sald": 26, "sald_fjol": 24,
        "yoy_pct": 25.1,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Sälen',
        "city": 'Sälen',
        "region": 'Dalarna',
        "lat": 61.1667, "lng": 13.2333,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 1274460, "oms_fjol": 3383224,
        "sald": 22, "sald_fjol": 51,
        "yoy_pct": -62.3,
        "kommentar": 'Ev rekrytering men det rullar på helt OK',
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Eslöv',
        "city": 'Eslöv',
        "region": 'Skåne',
        "lat": 55.8375, "lng": 13.3033,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 984112, "oms_fjol": 1077174,
        "sald": 17, "sald_fjol": 25,
        "yoy_pct": -8.6,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Katrineholm/Flen',
        "city": 'Katrineholm/Flen',
        "region": 'Mälardalen',
        "lat": 58.9986, "lng": 16.2081,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 641600, "oms_fjol": 439760,
        "sald": 13, "sald_fjol": 10,
        "yoy_pct": 45.9,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Sjöbo',
        "city": 'Sjöbo',
        "region": 'Skåne',
        "lat": 55.6333, "lng": 13.7167,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 407060, "oms_fjol": 706472,
        "sald": 8, "sald_fjol": 12,
        "yoy_pct": -42.4,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Höllviken',
        "city": 'Höllviken',
        "region": 'Skåne',
        "lat": 55.4167, "lng": 12.9667,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 296400, "oms_fjol": 741360,
        "sald": 4, "sald_fjol": 11,
        "yoy_pct": -60.0,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Söderhamn/Hudiksvall/Bollnäs',
        "city": 'Söderhamn/Hudiksvall/Bollnäs',
        "region": 'Gävleborg',
        "lat": 61.3036, "lng": 17.0572,
        "kategori": 'UTMANINGAR',
        "prio": '5', "prio_num": 5.0,
        "oms": 186000, "oms_fjol": 318840,
        "sald": 4, "sald_fjol": 8,
        "yoy_pct": -41.7,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Varberg',
        "city": 'Varberg',
        "region": 'Halland',
        "lat": 57.1057, "lng": 12.2508,
        "kategori": 'PROBLEM',
        "prio": '5', "prio_num": 5.0,
        "oms": 182520, "oms_fjol": 89600,
        "sald": 4, "sald_fjol": 1,
        "yoy_pct": 103.7,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Åre',
        "city": 'Åre',
        "region": 'Norrland',
        "lat": 63.3986, "lng": 13.0817,
        "kategori": 'OK',
        "prio": '5', "prio_num": 5.0,
        "oms": 71500, "oms_fjol": 0,
        "sald": 2, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Landskrona',
        "city": 'Landskrona',
        "region": 'Skåne',
        "lat": 55.8708, "lng": 12.8305,
        "kategori": 'PROBLEM',
        "prio": '5', "prio_num": 5.0,
        "oms": 0, "oms_fjol": 0,
        "sald": 0, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Kungsbacka',
        "city": 'Kungsbacka',
        "region": 'Västra Götaland',
        "lat": 57.4875, "lng": 12.0761,
        "kategori": 'PROBLEM',
        "prio": '5', "prio_num": 5.0,
        "oms": 0, "oms_fjol": 0,
        "sald": 0, "sald_fjol": 0,
        "yoy_pct": None,
        "kommentar": None,
        "recommended_action": None,
    },
    {
        "name": 'Skandiamäklarna Kungälv',
        "city": 'Kungälv',
        "region": 'Västra Götaland',
        "lat": 57.8708, "lng": 11.9803,
        "kategori": 'UTMANINGAR',
        "prio": '3 till 4', "prio_num": 3.5,
        "oms": 2066080, "oms_fjol": 1743418,
        "sald": 39, "sald_fjol": 35,
        "yoy_pct": 18.5,
        "kommentar": 'Ingen tillväxt',
        "recommended_action": None,
    },
]

# Kommersiella / vilande enheter utan tilldelad prioritet i underlaget
EXTRA_UNITS: list[dict] = [
    {
        "name": 'SkandiaMäklarna Småland Kommersiella',
        "oms": 525440, "oms_fjol": 934000,
    },
    {
        "name": 'SkandiaMäklarna Malmö City',
        "oms": 0, "oms_fjol": 34600,
    },
    {
        "name": 'SkandiaMäklarna Lomma',
        "oms": 0, "oms_fjol": 2000,
    },
    {
        "name": 'SkandiaMäklarna Årsta',
        "oms": 0, "oms_fjol": 0,
    },
    {
        "name": 'SkandiaMäklarna Svedala/Bara',
        "oms": 0, "oms_fjol": 0,
    },
    {
        "name": 'SkandiaMäklarna Stockholm Kommersiella',
        "oms": 0, "oms_fjol": 0,
    },
    {
        "name": 'SkandiaMäklarna Stenungsund',
        "oms": 0, "oms_fjol": 0,
    },
    {
        "name": 'SkandiaMäklarna Kommersiella S & Ö AB',
        "oms": 0, "oms_fjol": 0,
    },
    {
        "name": 'SkandiaMäklarna Ale',
        "oms": 0, "oms_fjol": 0,
    },
    {
        "name": 'SkandiaMäklarna AB',
        "oms": 0, "oms_fjol": 0,
    },
    {
        "name": 'SkandiaMäklarna Finspång',
        "oms": 0, "oms_fjol": 0,
    },
]
